/*
 * Decompiled with CFR 0.152.
 */
package com.rs2;

import com.rs2.model.combat.AttackBonusType;
import com.rs2.model.combat.AttackStyleDefinition;
import com.rs2.model.combat.AttackXpMode;
import com.rs2.model.combat.CombatType;
import java.math.BigInteger;

public final class ServerSettings {
    public static boolean mod2hsEnabled = false;
    public static double mod2hsAttackBonusRate = 1.2;
    public static double mod2hsStrengthBonusRate = 1.2;
    public static boolean wildyBotsUseNewGeneration = false;
    public static int wildyBotsBaseCombatLevel = 50;
    public static int wildyBotsCombatLevelSpread = 5;
    public static boolean wildyBotsIgnoreCombatForDeepWilderness = true;
    public static boolean relogFrozenBotsEnabled = false;
    public static boolean modernCombatSystemEnabled = true;
    public static boolean mysqlHiscoresEnabled = true;
    public static boolean k = false;
    public static boolean l = false;
    public static boolean broadcastCheatUsageEnabled = true;
    public static int defaultMovementSystem = 1;
    public static String serverVersion = "v4.5";
    public static int cacheVersion = 377;
    public static boolean skipUndefinedNpcSpawns = true;
    public static int maxLevel = 99;
    public static boolean capXpAtMaxLevel = false;
    public static double barrowsRewardRate = 1.0;
    public static int randomEventsMode = 0;
    public static int holidayDropSets = 50;
    public static int holidayDropRespawnTicks = 500;
    public static boolean holidayItemDropsEnabled = true;
    public static int membershipDaysPerPurchase = 14;
    public static boolean content2007Enabled = false;
    public static int fightCaveStartWaveZeroBased = 0;
    public static int rareDropChanceDivisor = -1;
    public static double commonDropRateMultiplier = 1.0;
    public static double uncommonDropRateMultiplier = 1.0;
    public static double rareDropRateMultiplier = 1.0;
    public static double veryRareDropRateMultiplier = 1.0;
    public static int dropRateCap = 512;
    public static boolean customDropRatesEnabled = false;
    public static String launcherJarPath = "";
    public static boolean cacheVerificationShutdownPending = true;
    public static int progressiveXpMode = 0;
    public static int groundItemLifetimeSeconds = 200;
    public static double shopRestockTimeMultiplier = 1.0;
    public static double shopItemMultiplier = 1.0;
    public static double itemRespawnDelayMultiplier = 1.0;
    public static double npcRespawnDelayMultiplier = 1.0;
    public static long Q = 0L;
    public static boolean showSkillUnlocks = false;
    public static boolean dynamicShopPricesEnabled = true;
    public static boolean T = false;
    public static boolean skipRequirementsForMissingQuests = false;
    public static boolean recolorMissingQuests = false;
    public static int completeMissingQuestsMode = 0;
    public static boolean clueMerchantEnabled = false;
    public static int clueMerchantClueLevel = 1;
    public static int clueMerchantPriceCoins = 50;
    public static boolean clanWarsBotsEnabled = false;
    public static int clanWarsTeamSize = 20;
    public static int clanWarsEventChanceDivisor = 24;
    public static boolean progressiveBotsPrioritizeExisting = false;
    public static boolean instantGrandExchangePriceFluctuationEnabled = true;
    public static boolean instantGrandExchangeEnabled = false;
    public static boolean grandExchangeServerOffersEnabled = true;
    public static int grandExchangeServerOfferCount = 200;
    public static boolean hotzonesForWildyBotsEnabled = false;
    public static boolean aj = false;
    public static boolean backupCharactersEnabled = false;
    public static boolean wildyBotsEnabled = false;
    public static boolean skillingBotsEnabled = false;
    public static boolean tradeBotsEnabled = false;
    public static boolean otherBotsEnabled = false;
    public static boolean progressiveBotsEnabled = false;
    public static boolean wcStyleMiningEnabled = false;
    public static boolean ar = false;
    public static boolean walkingBotsEnabled = false;
    public static boolean lanConnectionsEnabled = false;
    public static int membershipRequirementMode = 0;
    public static int membershipRequirementValue = 0;
    public static boolean idleLogoutEnabled = true;
    public static int otherBotCount = 20;
    public static int skillingBotCount = 50;
    public static int tradeBotCount = 50;
    public static int progressiveBotCount = 10;
    public static boolean freeToPlayWorld = true;
    public static boolean wildernessSlayerEnabled;
    public static int botLoginIdLimit;
    public static boolean aE;
    public static boolean aF;
    public static boolean aG;
    public static boolean aH;
    public static boolean aI;
    public static boolean grandExchangeEnabled;
    public static boolean tutorialSkipPromptEnabled;
    public static boolean aL;
    public static String serverName;
    public static String serverEmulatorName;
    public static boolean showServerEmulatorInWelcome;
    public static String mysqlDriverClass;
    public static String mysqlJdbcUrl;
    public static String mysqlUsername;
    public static String mysqlPassword;
    public static boolean mysqlPlayerSaveEnabled;
    public static boolean debugModeEnabled;
    public static boolean developModeEnabled;
    public static boolean controlPanelHiscoresEnabled;
    public static boolean adminInteractionsAllowed;
    public static int serverPort;
    public static boolean itemSpawningEnabled;
    public static boolean funPkEnabled;
    public static boolean pkWorldEnabled;
    public static int loginRestrictionMode;
    public static boolean rsaEnabled;
    public static boolean be;
    public static int clientBuild;
    public static String rsaModulusString;
    public static String rsaPrivateExponentString;
    public static BigInteger rsaModulus;
    public static BigInteger rsaPrivateExponent;
    public static double xpRate;
    public static double questXpRate;
    public static double botXpRateMultiplier;
    public static int botXpRateMode;
    public static int startX;
    public static int startY;
    public static int startPlane;
    public static int respawnX;
    public static int respawnY;
    public static int respawnPlane;
    public static int maxPlayers;
    public static final String[] bonusTypeNames;
    public static boolean diseasingEnabled;
    public static boolean agilityEnabled;
    public static boolean cookingEnabled;
    public static boolean craftingEnabled;
    public static boolean farmingEnabled;
    public static boolean firemakingEnabled;
    public static boolean fishingEnabled;
    public static boolean fletchingEnabled;
    public static boolean herbloreEnabled;
    public static boolean miningEnabled;
    public static boolean prayerEnabled;
    public static boolean runecraftingEnabled;
    public static boolean slayerEnabled;
    public static boolean smithingEnabled;
    public static boolean thievingEnabled;
    public static boolean woodcuttingEnabled;
    public static boolean duelingDisabled;
    public static final int[] DEFAULT_WEAPON_MOVEMENT_ANIMATIONS;
    public static AttackStyleDefinition MAGIC_ATTACK_STYLE;
    public static AttackStyleDefinition DRAGONFIRE_ATTACK_STYLE;
    public static AttackStyleDefinition SARADOMIN_SWORD_ATTACK_STYLE;
    public static final int[] FUN_WEAPON_IDS;
    public static int placeholderObjectId;
    public static final int[] PACKET_LENGTHS;
    public static final int[][][] APPEARANCE_COLOR_RANGES;
    public static final int[][][] APPEARANCE_BODY_PART_RANGES;

    static {
        botLoginIdLimit = 1990;
        aE = false;
        aF = false;
        aG = false;
        aH = false;
        aI = false;
        grandExchangeEnabled = false;
        tutorialSkipPromptEnabled = true;
        aL = false;
        serverName = "RuneScape";
        serverEmulatorName = "EasyRS2";
        showServerEmulatorInWelcome = true;
        mysqlDriverClass = "com.mysql.jdbc.Driver";
        mysqlJdbcUrl = "jdbc:mysql://localhost/2006sp_main";
        mysqlUsername = "root";
        mysqlPassword = "";
        mysqlPlayerSaveEnabled = false;
        debugModeEnabled = false;
        adminInteractionsAllowed = true;
        serverPort = 43594;
        loginRestrictionMode = 0;
        rsaEnabled = false;
        be = false;
        clientBuild = 317;
        rsaModulusString = "126281243334509621910786157961571648139029640444686961553514423188662257084412132099345405190869140255510782101811050242941632064063371431334829733868500675557132805905863594614007916107891529024023784039950030199813062171961096886168210646453313260607895180672957089197913358703168034604511968295223858703073";
        rsaPrivateExponentString = "30652639256685216982113709825788207861142309232862050206651318249008028834075838037084192223878820867367525545502695992564741792805897626221439361069016103707546910916876758973004891298232729104728327473982300624040057756427674392115989911877923828003372350341670381425233062849579939381994254110724498182865";
        rsaModulus = new BigInteger(rsaModulusString);
        rsaPrivateExponent = new BigInteger(rsaPrivateExponentString);
        xpRate = 40.0;
        questXpRate = 40.0;
        botXpRateMultiplier = 40.0;
        botXpRateMode = 1;
        startX = 3093;
        startY = 3104;
        startPlane = 0;
        respawnX = 3222;
        respawnY = 3218;
        respawnPlane = 0;
        maxPlayers = 3000;
        bonusTypeNames = new String[]{"Stab", "Slash", "Crush", "Magic", "Range", "Stab", "Slash", "Crush", "Magic", "Range", "Strength", "Prayer", "Strength Ranged", "Strength Magic"};
        diseasingEnabled = true;
        agilityEnabled = false;
        cookingEnabled = true;
        craftingEnabled = true;
        farmingEnabled = true;
        firemakingEnabled = true;
        fishingEnabled = true;
        fletchingEnabled = true;
        herbloreEnabled = true;
        miningEnabled = true;
        prayerEnabled = true;
        runecraftingEnabled = true;
        slayerEnabled = true;
        smithingEnabled = true;
        thievingEnabled = true;
        woodcuttingEnabled = true;
        duelingDisabled = false;
        DEFAULT_WEAPON_MOVEMENT_ANIMATIONS = new int[]{808, 819, 824};
        MAGIC_ATTACK_STYLE = new AttackStyleDefinition(CombatType.MAGIC, AttackXpMode.MAGIC, AttackBonusType.MAGIC);
        DRAGONFIRE_ATTACK_STYLE = new AttackStyleDefinition(CombatType.MAGIC, AttackXpMode.DRAGONFIRE, AttackBonusType.MAGIC);
        SARADOMIN_SWORD_ATTACK_STYLE = new AttackStyleDefinition(CombatType.MAGIC, AttackXpMode.SARADOMIN_SWORD, AttackBonusType.SLASH);
        (new int[1])[0] = 6529;
        FUN_WEAPON_IDS = new int[]{4566, 1419, 2460, 2462, 2464, 2466, 2468, 2470, 2472, 2474, 2476, 8936, 8938};
        placeholderObjectId = 3550;
        int[] nArray = new int[257];
        nArray[3] = 1;
        nArray[4] = -1;
        nArray[11] = 1;
        nArray[14] = 4;
        nArray[16] = 6;
        nArray[17] = 2;
        nArray[18] = 2;
        nArray[19] = 2;
        nArray[21] = 2;
        nArray[23] = 6;
        nArray[25] = 12;
        nArray[35] = 8;
        nArray[36] = 4;
        nArray[39] = 2;
        nArray[40] = 2;
        nArray[41] = 6;
        nArray[43] = 6;
        nArray[45] = -1;
        nArray[53] = 12;
        nArray[57] = 8;
        nArray[58] = 8;
        nArray[59] = 12;
        nArray[60] = 8;
        nArray[61] = 8;
        nArray[70] = 6;
        nArray[72] = 2;
        nArray[73] = 2;
        nArray[74] = 8;
        nArray[75] = 6;
        nArray[77] = -1;
        nArray[79] = 6;
        nArray[85] = 1;
        nArray[86] = 4;
        nArray[87] = 6;
        nArray[95] = 3;
        nArray[98] = -1;
        nArray[101] = 13;
        nArray[103] = -1;
        nArray[117] = 6;
        nArray[120] = 1;
        nArray[122] = 6;
        nArray[126] = -1;
        nArray[128] = 2;
        nArray[129] = 6;
        nArray[131] = 4;
        nArray[132] = 6;
        nArray[133] = 8;
        nArray[135] = 6;
        nArray[139] = 2;
        nArray[145] = 6;
        nArray[152] = 1;
        nArray[153] = 2;
        nArray[155] = 2;
        nArray[156] = 6;
        nArray[164] = -1;
        nArray[165] = -1;
        nArray[181] = 8;
        nArray[183] = 3;
        nArray[185] = 2;
        nArray[188] = 8;
        nArray[189] = 1;
        nArray[192] = 12;
        nArray[200] = 2;
        nArray[208] = 4;
        nArray[210] = 4;
        nArray[214] = 9;
        nArray[215] = 8;
        nArray[218] = 10;
        nArray[222] = 3;
        nArray[226] = -1;
        nArray[228] = 6;
        nArray[230] = 1;
        nArray[234] = 6;
        nArray[236] = 6;
        nArray[237] = 8;
        nArray[238] = 1;
        nArray[241] = 4;
        nArray[246] = -1;
        nArray[248] = -1;
        nArray[249] = 4;
        nArray[252] = 6;
        nArray[253] = 6;
        PACKET_LENGTHS = nArray;
        APPEARANCE_COLOR_RANGES = new int[][][]{new int[][]{new int[5], {11, 15, 15, 5, 7}}, new int[][]{new int[5], {11, 15, 15, 5, 7}}};
        int[][][] nArrayArray = new int[2][][];
        int[][] nArrayArray2 = new int[2][];
        int[] nArray2 = new int[7];
        nArray2[0] = 18;
        nArray2[1] = 26;
        nArray2[2] = 36;
        nArray2[4] = 33;
        nArray2[5] = 42;
        nArray2[6] = 10;
        nArrayArray2[0] = nArray2;
        nArrayArray2[1] = new int[]{25, 32, 41, 9, 35, 44, 17};
        nArrayArray[0] = nArrayArray2;
        nArrayArray[1] = new int[][]{{56, 61, 70, 45, 67, 79, -1}, {60, 66, 78, 55, 69, 81, -1}};
        APPEARANCE_BODY_PART_RANGES = nArrayArray;
    }
}

